// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("HostBox")]
[assembly: AssemblyProductAttribute("HostBox")]
[assembly: AssemblyDescriptionAttribute("The host of plugin applications.")]
[assembly: AssemblyVersionAttribute("1.0.3")]
[assembly: AssemblyFileVersionAttribute("1.0.3")]
[assembly: AssemblyInformationalVersionAttribute("1.0.3")]
[assembly: AssemblyCopyrightAttribute("MIT License")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.3";
    }
}
